### ISSUE TITLE
Index is copied without mapping

### ISSUE THREAD

**Issue by tiferet** [mallocator/Elasticsearch-Exporter#115] opened 2016-01-10 14:18 UTC
I am trying to copy an index from one server to another with the command:
```
node  exporter.js -sh localhost -th 10.2.16.225
```
The index gets copied over without my mapping, and is given some default mapping. If I try to set the mapping with Sense before carrying out the copy, while copying the indexing is computed all over again. If I try to first do the copy and then set the mapping I get an error that the index already exists.

My indexing involves carrying out a time-consuming NLP algorithm on the indexed texts, so carrying out the indexing all over again just to copy an index over to a new server isn't an option. Is there a different way I should be using this tool?

Thank you!

**Comment by mallocator** [comment] 2016-01-10 19:58
Hi, which version are of the exporter are you using? Version 2.0 is still in beta and has a number of known bugs that haven't been addressed yet. If you want to use something that works stick to the version published on npm.

If you want to keep using the 2.0 version, there's an option to skip the mapping step completely and just assume that there's an existing index.

In the end the right behaviour would be to properly copy over the existing mapping or to just print a warning if the index already exists.

Also if you're using any tokenizers/analyzers that are defined in the elasticsearch configuration, you have to make sure that these are also available on the target machine, otherwise the indexer will reference non-existent entities.

**Comment by tiferet** [comment] 2016-01-14 07:22
I've tried both versions and I get the same problem with both. I am fine with using the published npm version. 

The tokenizers and analyzers exist also on the target machine. The indexing is able to access them and work fine on the target machine, but the problem is that re-indexing takes a long time and I don't want to have to re-index after the copy. 

What should I do differently in order to ensure that I properly copy over the existing mapping?

Thank you!

**Comment by mallocator** [comment] 2016-01-14 18:52
Hmm so just to clarify: The mapping is actually there, you just don't want the new cluster to reindex every document. The exporter will only copy the mapping definition. If you copy your documents into a new index, the analyzers will have to run again. If you want to migrate indices along with your data you will have to look for another solution, maybe somehow copying the actual data files of ElasticSearch.

On the other hand if the mapping isn't even copied over properly, then I will need some more info, such as what parameters you used and what your current mapping looks like, to reproduce the error

**Comment by mallocator** [comment] 2016-06-06 20:58
Closing this since no new information has been provided.

**Closed by mallocator** 2016-06-06 20:58 UTC
Labels: bug, ES Scroll Driver, need feedback
