### ISSUE TITLE
Index is only partially copied 

### ISSUE THREAD

**Issue by bemeyert** [mallocator/Elasticsearch-Exporter#113] opened 2015-11-04 15:16 UTC
Command and output was:
```
[root@salttestvm70 Elasticsearch-Exporter]# node exporter.js -th localhost -si logstash-2015.10.19 -sh other-host   
Elasticsearch Exporter - Version 2.0.0
Mapping on target database is now ready
Starting data export
Fetched Entries:467 of 10 documentstries (100%)
Processed Entries:	0 documents
Source DB Size:		0 documents
```
Size of the original/source index on "other-host":
```
[root@other-host logstash-2015.10.19]# du -hs *
19G	0
19G	1
19G	2
19G	3
19G	4
60K	_state
```
Size of the index on the target host:
```
[root@salttestvm70 logstash-2015.10.19]# du -hs *
38M	0
36M	1
38M	2
30M	3
37M	4
56K	_state
```

**Comment by mallocator** [comment] 2015-11-04 16:32
Probably related/duplicate of #108

**Comment by mallocator** [comment] 2016-06-07 00:25
Can't recreate with the data I have. Need more info such as the source data to continue debugging.

**Closed by mallocator** 2016-06-07 00:25 UTC
Labels: bug, ES Scroll Driver
